export const ROUTES = {
    MAIN: '/',
    FOREIGN_ADDRESSES: '/foreign-addresses',
    MY_ORDERS: '/my-orders',
    BOXES: '/boxes',
    COURIER: '/courier',
    REBATES: '/rebates',
    BALANCE: '/balance',
    BALANCE_INCREASE: '/balance-increase',
    BALANCE_PAY_TR: '/balance-paytr',
    APPLICATIONS: '/applications',
    APPLICATION_CHAT: '/application/:id',
    APPLICATION_FORM: '/new-application',
    ONLINE_QUEUE: '/online-queue',
    SETTINGS: '/settings',
    LOGOUT: '/logout',
    NOTIFICATIONS: '/notifications',
    SATISFACTION: '/satisfaction/:id',
    DECLARE: '/declare',
};
