export const ROUTES = {
    MAIN: '/dashboard',
    FOREIGN_ADDRESSES: '/foreign-addresses',
    MY_ORDERS: '/my-orders',
    BOXES: '/boxes',
    COURIER: '/courier',
    REBATES: '/rebates',
    BALANCE: '/balance',
    BALANCE_INCREASE: '/balance-increase',
    BALANCE_PAY_TR: '/balance-paytr',
    APPLICATIONS: '/applications',
    ONLINE_QUEUE: '/online-queue',
    SETTINGS: '/settings',
    LOGOUT: '/logout',
};
